# Generated by Django 5.0.1 on 2024-02-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='text_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.choice'),
        ),
    ]
