# Generated by Django 5.0.1 on 2024-02-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userresponse_text_response_alter_userresponse_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='app.question'),
        ),
        migrations.CreateModel(
            name='QuestionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='app.question')),
                ('parent_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_questions', to='app.choice')),
            ],
        ),
    ]
